config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
	devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	get '/trips/explore', to: 'trips#explore'
	resources :trips do
		resources :photos
	end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
		user ||= User.new # guest user (not logged in)
		can :read, Trip

		can [:create, :update, :destroy], Trip do |trip|
		trip.user == user
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :trip
	mount_uploader :image, ImageUploader
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user
	has_many :photos, dependent: :destroy 
	accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :trips, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :authenticate_user!
	include CanCan::ControllerAdditions
	
#	flash[:notice] = "Access denied!"
#	flash.keep(:notice)
#	redirect_to root_url
#end
end

app/controllers/photos_controller.rb
#before_action :set_trip

class PhotosController < ApplicationController
	def index
		@trip = Trip.find(params[:trip_id])
    @photos = @trip.photos.all
		
	end
	
	def show
		@trip = Trip.find(params[:trip_id])
    @photo = @trip.photos.find(params[:id])
	end
	
	def new
		@trip = Trip.find(params[:trip_id])
    @photo = @trip.photos.new(params[:id])
	end
	
	def create
		@trip = Trip.find(params[:trip_id])
		@photo = @trip.photos.build(photo_params) 
#		@photo.trip_id = @trip.id
		redirect_to trip_path(@trip)
	end
	
	def edit
		@trip = Trip.find(params[:trip_id])
    @photo = @trip.photos.find(params[:id])
#		@photos = Photo.where(trip_id: @trip.id)
	end
	
	def update
	 @trip = Trip.find(params[:trip_id])
   @photo = @trip.photos.find(params[:id])
   @photo.update(photo_params)
   redirect_to trip_path(@trip)
#redirect_to @trip
	end
	
	def destroy
    @trip = Trip.find(params[:trip_id])
    @photo = @trip.photos.find(params[:id])

    @photo.destroy
    redirect_to trip_path(@trip)
  end
	
	private
	
	def photo_params
		params.require(:photo).permit(:description, :photo_url, :image)
	end
	
#	def set_trip  
#  	@trip = Trip.find(params[:trip_id])
#	end  
	
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
	before_filter :authenticate_user!, except: [:index]
	def index
		@trips = Trip.all
#		@trips = Trip.pluck(:city).uniq
  	@home_page = true

	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	load_and_authorize_resource only: [:edit, :update, :destroy]
	
	def index
		@user = current_user
		@trips = current_user.trips
		
#		Trip.pluck(:city).uniq-->
	end
	
	def explore
		@trips = Trip.all
		@photos = Photo.all
#		@user = @trip.user
	end
	
	def show
		@user = current_user
		@trip = Trip.find(params[:id])
#		@photos = Photo.where(trip_id: @trip.id)
	end
	
	def new
		@trip = current_user.trips.build
		@photo = @trip.photos.build
#		3.times { @trip.photos.build}
	end 
	
	def create
#		@user = current_user
#		@trip = @user.trips.build(trip_params)
		@trip = current_user.trips.build(trip_params)
		if @trip.save
			# to handle multiple images upload on create
#			params[:photos]['image'].each do |a|
#          @photo = @trip.photos.create!(:image => a)
#       end
      redirect_to trips_url
    else
      render 'new'
    end
	end
	
	def edit
		@trip = Trip.find(params[:id])
		3.times { @trip.photos.build}
	end
	
	def update
		@trip = Trip.find(params[:id])
		@trip.update(trip_params)
		redirect_to trips_path
	end
	
	def destroy
		@trip = Trip.find(params[:id])
		@trip.destroy
		redirect_to trips_path
	end
	
	private 
	def trip_params
		params.require(:trip).permit(:user_id, :city, :country, photos_attributes: [:id, :photo_url, :description, :image])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper  
 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
	
	def link_to_add_fields(name = nil, f = nil, association = nil, options = nil, html_options = nil, &block) 
		# If a block is provided there is no name attribute and the arguments are shifted with one position to the left. This re-assigns those values. 
		f, association, options, html_options = name, f, association, options if block_given? 
		options = {} if options.nil? 
		html_options = {} if html_options.nil? 
		if options.include? :locals 
			locals = options[:locals] 
		else 
			locals = { } 
		end 
		if options.include? :partial 
			partial = options[:partial] 
		else 
			partial = association.to_s.singularize + '_fields' 
		end 
		# Render the form fields from a file with the association name provided 
		new_object = f.object.class.reflect_on_association(association).klass.new 
		fields = f.fields_for(association, new_object, child_index: 'new_record') do |builder| 	
			render(partial, locals.merge!( f: builder)) 
		end 
		# The rendered fields are sent with the link within the data-form-prepend attr 
		html_options['data-form-prepend'] = raw CGI::escapeHTML( fields ) 
		html_options['href'] = '#' 

		content_tag(:a, name, html_options, &block) 
	end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "WanderList" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Amatic+SC|Architects+Daughter|Josefin+Sans|Shadows+Into+Light' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="header">
      <h1 class="main-header"><a class="headline" href="/">WanderList</a></h1>
        <ul class="header-subnav">
          <div class="top-bar">
            <% if user_signed_in? %>
              <div class="top-bar-left">
            	  <ul class="menu"></ul>
            	     <li><a href='/trips/'><%= current_user.username %>'s List</a></li>
              </div>
              <div class="top-bar-right">
                <ul class="menu">
            			<li><%= link_to 'Explore', trips_explore_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
          	<% else %>
          	    <ul class="menu">
          			  <li><a data-open="loginmodal">LOGIN</a><%= render "splash/loginmodal" %></li>
          			  <li><a data-open="signupmodal">SIGNUP</a><%= render "splash/signupmodal" %></li>
          	<% end %>
                </ul>
              </div>
          </div>
        </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<html>

<body>
  <h1>PHOTO _form.html.erb</h1>
    <%= form_for([@trip, @photo]) do |f| %>
      <p><%= f.text_area :description, placeholder: "description" %></p>

  		<div class="field">
  				add an image....
  				<%= f.file_field :image, class:"fancy radius button" %>
  		</div>

      <p><%= f.submit %></p>
  <!--<= link_to 'Add Photo', photo_path(@photo) %>		-->
  <!--<= link_to 'Add Photo', trip_path(@trip) %>-->
    <% end %>
</body>

</html>

app/views/photos/_photo.html.erb
<html>

<body>
	<div class="polaroidcontainer">
		<div class="image">
			<%= image_tag(photo.image_url(:normal).to_s) %>
			<% @trip.photos.each do |photo| %>
			<%= photo.description %>
			<!--	<= link_to 'Edit Photo', edit_trip_photo_path(@trip) %>-->
			<% if current_user.id == @trip.user_id %>
  				<%= link_to 'Destroy Photo', [photo.trip, photo],
              method: :delete,
              data: { confirm: 'Are you sure?'} %>
			<% end %>
		</div>
		<% end %>
	</div>
</body>

</html>

app/views/photos/edit.html.erb
<html>

<body>
  <h1>Photo eidt.html.erb (WORKING)</h1>

  <%= form_for([@trip, @photo]) do |f| %>
    <p><%= f.text_area :description, placeholder: "description" %></p>
		<div class="field">
				add an image....
				<%= f.file_field :image %>
		</div>
    <p><%= f.submit %></p>
    <!--<= link_to 'Add Photo', photo_path(@photo) %>		-->
    <!--<= link_to 'Add Photo', trip_path(@trip) %>-->
  <% end %>
    <!--<= render 'form', photo: @photo %>-->
</body>

</html>

app/views/photos/index.html.erb
<html>

<body>
  <div class="photoindex">
    <h2><%= @trip.user.username %>'s trip to: </h2>
    <h4><%= @trip.city %>, <%= @trip.country %></h4>
  </div>

  <div class="polaroidcontainer">
    <% @photos.each do |photo| %>
      <div class="polaroid">
        <div class="polaroid-image">
          <%= image_tag(photo.image_url(:resize).to_s) %>
        </div>
        <div class="polaroid-bottom">
          <%= photo.description %>
        </div>
      </div>
    <% end %>
  </div>
  <!--<= image_tag(@photo.image_url.to_s) %>-->
</body>

</html>

app/views/photos/new.html.erb
<html>

<body>
  <h1>NEW PHOTO HONEYYYYY</h1>
  <%= render 'form', photo: @photo %>
</body>

</html>

app/views/photos/show.html.erb
<html>

<body>
  <h1>PHOTOs show.html.erb (WORKING)</h1>
  <%= image_tag(@photo.image_url.to_s) %>
</body>

</html>

app/views/splash/_loginmodal.html.erb
<html>

<body>
  <div class="reveal" id="loginmodal" data-reveal>
    <p class="lead">
      <h2>Log in</h2>

      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="field">
            <%= f.text_field :username, placeholder: "username", autofocus: true  %>
          </div>

          <div class="field">
            <%= f.email_field :email, placeholder: "email" %>
          </div>

          <div class="field">
            <%= f.password_field :password, placeholder: "password", autocomplete: "off" %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <a class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </a>
          <% end %>

          <div class="row">
            <div class="actions">
              <%= f.submit "			Log in			", class:"fancy radius button" %>
            </div>
          </div>
      <% end %>
  <br>
      <!-- <p>Don't have an account?</p> -->
      <!-- <%= render "devise/shared/links" %> -->
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</body>

</html>

app/views/splash/_signupmodal.html.erb
<html>

<body>
  <div class="reveal" id="signupmodal" data-reveal>
    <p class="lead">
      <h2>Sign up</h2>
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
          <div class="field">
              <%= f.text_field :username, placeholder: "username", autofocus: true  %>
          </div>

          <div class="field">
              <%= f.email_field :email, placeholder: "email" %>
          </div>

          <div class="field">
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %>
                characters minimum)</em>
              <% end %>
              <%= f.password_field :password, placeholder: "password", autocomplete: "off" %>
          </div>

          <div class="field">
              <%= f.password_field :password_confirmation, placeholder: "confirm password", autocomplete: "off" %>
          </div>

          <br>

          <div class="actions">
              <div class="row">
                <a><%= f.submit "			Sign Up			", class:"fancy radius button" %></a>
              </div>
          </div>

          <br>
      <% end %>
        <!-- <p>
            <h6>Already a member?</h6>
        </p> -->
        <!--extracted from render devise/shared/links-->
        <!-- <%= render "devise/shared/links" %> -->
    <!--MODAL CLOSE BUTTON  -->
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
</body>

</html>

app/views/splash/index.html.erb
<html>

<body class="<%= @home_page ? 'homepage' : ''%>">
	<div class="splash-wrapper">
	<% if user_signed_in? %>
			<div>
				<button><%= link_to 'My WanderList', trips_path, :class => 'button-gradient' %></button>
				<button><%= link_to 'Start Exploring', trips_explore_path, :class => 'button-gradient' %></button>
			</div>
	</div>
	<% else %>
		<div class="splash-tagline">
			<p>Sign Up.</p>
			<p>Share your experiences.</p>
			<p>Find inspiration.</p>
		</div>
	<% end %>
	<%= yield %>
</body>

</html>

app/views/trips/_form.html.erb
<html>

<body>
  <div class="tripform">
    <%= form_for @trip do |f| %>
      <% if trip.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(trip.errors.count, "error") %>
                prohibited this trip from being saved:</h2>
            <ul>
                <% trip.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
      <% end %>

      <div>
          <%= f.text_field :city, placeholder: "city" %>
      </div>

      <div>
          <%= f.text_area :country, placeholder: "country" %>
      </div>

      <%= f.fields_for :photos do |photos_form| %>
        <%= render 'trip', photos_form: photos_form %>
      <% end %>

      <div>
          <%= f.submit "add trip", class:"fancy radius button" %>
      </div>
    <% end %>
  </div>
</body>

</html>

app/views/trips/_trip.html.erb
<html>

<body>
  <div class="photoform">
      <div>
        <%= photos_form.text_field :description, placeholder: "description" %>
      </div>
			<div>
				add an image....
        <div>
				  <%= photos_form.file_field :image %>
        </div>
			</div>
  </div>
</body>

</html>

app/views/trips/edit.html.erb
<html>

<body>
  <h1>Edit honey!!!</h1>
  <%= render 'form', trip: @trip %>
  <%= link_to 'Back', trips_path %>
</body>

</html>

app/views/trips/explore.html.erb
<html>

<body>
  <div class="explorecontainer">
    <h1>Explore</h1>
      <% @trips.each do |trip| %>
      <div class="image">
          <figure class="cap-bot">
              <div class="overlay">
                  <a><%= trip.user.username %>'s trip to</a>
                  <br>
                  <a id="tripcity"><%= trip.city %></a>
                  <br>
                  <a><%= trip.country%></a>
              </div>
              <%= image_tag(trip.photos.first.image_url(:resize).to_s) %>
              <%= link_to trip_photos_path(trip)do%>
              <figcaption>
                  <%= trip.photos.count %>
                  photos
              </figcaption>
              <% end %>
          </figure>
      </div>
      <% end %>
  </div>
</body>

</html>

app/views/trips/index.html.erb
<html>

<body>
	<div class='trips-container'>
		<h1>Where I've been</h1>

			<% if @trips.count == 0 %>
				<!-- <p>Add your first trip!</p> -->
			<% else %>

			<% @trips.each do |trip| %>
				<div class="image">
					<figure class="cap-bot">
						<div class="overlay2">
							<h4><%= link_to trip_photos_path(trip) do %>
									<%= trip.city %></h4>
						</div>
							<% end %>
							<%= image_tag(trip.photos.first.image_url(:resize).to_s) %>
							<figcaption>
								<div id="tripedit">
									<a><%= link_to 'Edit', edit_trip_path(trip) %></a>
								</div>
								<div id="tripdelete">
									<a><%= link_to 'Destroy', trip_path(trip),
											method: :delete,
											data: { confirm: 'Are you sure?' } %></a>
								</div>
							</figcaption>
					</figure>
				</div>
			<% end %>
		<% end %>
		<div class="addtrip">
			<button><%= link_to 'Add A Trip', new_trip_path, class: 'button-gradient' %></button>
		</div>
	</div>
	<!-- <div>
		<h1>You're Going</h1>
	</div> -->
</body>

</html>

app/views/trips/new.html.erb
<html>

<body>
  <div class="newtripform">
    <h1>Share an experience!</h1>

    <%= render 'form', trip: @trip %>

    <!--<= render 'photos/form', photo: @photo  %>-->

    <button class="fancy radius button"><%= link_to 'Back', trips_path %></button>
  </div>
</body>

</html>

app/views/trips/show.html.erb
<html>
<!-- Not using this page... link_to trip_photos_path(trip) (photos.index.html.erb) in index and explore instead -->
<body>
	<h4><%= @trip.user.username %>'s trip to: </h4>
	<h4><%= @trip.city %>, <%= @trip.country %></h4>

		<%= render @trip.photos %>
	<div>
		<p><% if current_user.id == @trip.user_id %>
				<a><%= link_to 'Edit Trip', edit_trip_path %></a>
	    	<a><%= link_to 'Delete Trip', trip_path,
	              method: :delete,
	              data: { confirm: 'Are you sure?' } %></a>
			<% end %></p>
	</div>
		<!--<= link_to 'Edit', edit_trip_path(@trip) %> |-->
		<%= link_to 'Go to your List', trips_path %>
		<%= link_to 'Explore more cities', trips_explore_path %>
</body>

</html>